trigger:
  branches:
    include:
      - dev
      - main
      - features/*
      - releases/*

variables:
  - group: registry-credentials
  - name: isDev
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: isRelease
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/release')]
  - name: tag
    value: '$(Build.BuildNumber)'
  - name: env
    ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
      value: Dev
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      value: QA
    ${{ if startsWith(variables['Build.SourceBranchName'], 'releases/release') }}:
      value: Prod

stages:
  - stage: Build
    displayName: Unit Tests, Sonar Scan, Build & Docker push
    jobs:
    - job: Build
      displayName: Unit Tests, Sonar Scan, Build & Docker push
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: JavaToolInstaller@0
        displayName: 'Installing Java 21'
        inputs:
          versionSpec: '21'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
      - task: Gradle@3
        displayName: 'Test and Publish Test Results'
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'clean build'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          #codeCoverageToolOption: 'JaCoCo'
          #codeCoverageClassFilesDirectories: 'build/classes/main/'
          #codeCoverageClassFilter: -:com.malli.accountservice.domain.*,-:com.malli.accountservice.config.*,-:com.malli.accountservice.exception.*
          javaHomeOption: 'JDKVersion'
          sonarQubeRunAnalysis: false
          spotBugsAnalysis: false
      # - task: SonarCloudPrepare@1
      #   displayName: Sonar Scan Prepare
      #   inputs:
      #     SonarCloud: 'sonarcloud' # 'sonarcloud' is service connection name
      #     organization: 'mallikarjunareddyn'
      #     scannerMode: 'CLI'
      #     configMode: 'file'
      # - task: SonarCloudAnalyze@1
      #   displayName: Sonar Scan Analyze
      #   inputs:
      #     jdkversion: 'JAVA_HOME_21_X64'
      # - task: SonarCloudPublish@1
      #   displayName: Sonar Publish
      #   inputs:
      #     pollingTimeoutSec: '300'
      - task: Gradle@3
        displayName: Docker Build & Push
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'jib -Djib.to.auth.username=$(REGISTRY_USERNAME) -Djib.to.auth.password=$(REGISTRY_PASSWORD) -Djib.to.tags=$(tag)'
